[package]
name = "dst-decoder"
version = "0.1.0"
edition = "2024"
description = "A Rust implementation of the MPEG-4 Part 3 Subpart 10 Direct Stream Transfer (DST) Audio compression format."
license = "Apache-2.0"
repository = "https://github.com/bleggett/dst-decoder"
exclude = [
    "src/test_fixtures/*",
]

[dependencies]
anyhow = "1.0.102"
